### ISSUE TITLE
touch_timeout is never used

### ISSUE THREAD

**Issue by anyn99** [cpldcpu/TinyTouchLib#2]
Don't know, if you are still looking after this code, but i found a small bug.

the define touch_timeout in tinytouchlib.h is never used to alter the timeout.
it is fixed in line 69 of tinytouchlib.c: 
"if (timer==255)"

**Comment by cpldcpu** [comment]
True! That is indeed a bug. Thanks for pointing out.

If you are playing around with the lib anyways, could you submit a pull request for the fix? Then I'll merge. I can't test right now.
