### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by imayoda** [cpldcpu/TinyTouchLib#4]
Hi there, I have a strange behavior right after #include "TinyTouchLib.h"..
after inclusion, code seems to generate same dimension (500byte circa) binary no matter what code comes after it..
I'm using arduino ide 1.0.6 + core13 on an attiny13A, is it wrong with that?
Any suggestions? 
Many thanks for all

**Comment by cpldcpu** [comment]
I am not quite sure about the exact issue. However the library is not specifically meant for arduino. it is quite possible there are some issues with that environment.
